# Generated by Django 3.0.6 on 2020-05-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200530_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tagline',
            field=models.TextField(default="I'm EPIC", max_length=200),
        ),
    ]
