# Generated by Django 3.0.6 on 2020-05-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200530_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(default='example.com', max_length=200),
        ),
    ]
