# Generated by Django 3.0.6 on 2020-05-31 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200530_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 6, 10, 29, 94356, tzinfo=utc)),
        ),
    ]
